package fakekube.io.api.impl;

import fakekube.io.api.*;
import fakekube.io.model.IoK8sApimachineryPkgApisMetaV1APIGroup;
import fakekube.io.utils.ResourceReader;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

import org.apache.cxf.jaxrs.model.wadl.Description;
import org.apache.cxf.jaxrs.model.wadl.DocTarget;

import org.apache.cxf.jaxrs.ext.multipart.*;

import io.swagger.annotations.Api;

/**
 * Kubernetes
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 */
public class AppsApiServiceImpl implements AppsApi {
    public Response getAppsAPIGroup() {
    	IoK8sApimachineryPkgApisMetaV1APIGroup obj = new ResourceReader().read("apps_groups.json", IoK8sApimachineryPkgApisMetaV1APIGroup.class);
        return (obj != null ? Response.ok(obj) : Response.status(Status.BAD_REQUEST)).build();
    }
    
}

