package fakekube.io.sim.metrics;

import java.util.logging.Logger;

import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;

import fakekube.io.model.IoK8sApiAppsV1Deployment;
import fakekube.io.model.IoK8sApimachineryPkgApisMetaV1APIResourceList;
import fakekube.io.utils.ResourceReader;

/**
 * Kubernetes
 *
 * <p>No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 */
public class MonitoringV1ApiServiceImpl implements MonitoringV1Api {
	private static final Logger LOGGER = Logger.getLogger(MonitoringV1ApiServiceImpl.class.getName());

	public Response getAppsV1APIResources() {
    	IoK8sApimachineryPkgApisMetaV1APIResourceList obj = new ResourceReader().read("monitoring_resources.json", IoK8sApimachineryPkgApisMetaV1APIResourceList.class);
        return (obj != null ? Response.ok(obj) : Response.status(Status.BAD_REQUEST)).build();
    }

	@Override
	public Response createMonitoringV1NamespacedPrometheus(String namespace, IoK8sApiMonitoringV1Prometheus body) {
		 LOGGER.info("received prometheus");
		 return Response.ok(body).build();	 
	}    
}

