apiVersion: v1
items:
- apiVersion: v1
  data:
    key1: value1
    key2: "2"
  kind: ConfigMap
  metadata:
    creationTimestamp: "2020-01-20T08:41:10Z"
    name: my-config-map
    namespace: default
    resourceVersion: "3604679"
    selfLink: /api/v1/namespaces/default/configmaps/my-config-map
    uid: d73530de-86ad-4e35-8c61-d74fabc97bc3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
