apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-default
  namespace: default
spec:
  containers:
  - name: demo-pod
    image: fakekube/test
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
